import time
import random


# Function to generate random contemporary dance moves
def generate_dance_moves(gcode_file):
    # Generate random movements within a 15x15 cm area (X=0 to 150, Y=0 to 150)
    for i in range(30):  # Generate 30 random moves
        x = random.uniform(0, 150)
        y = random.uniform(0, 150)
        z = random.uniform(0.2, 2)  # Random Z height for bouncing (min 0.2 mm)
        feed_rate = random.randint(800, 2000)  # Random feed rate for dynamic speed

        gcode_file.write(
            f"G1 X{x:.2f} Y{y:.2f} Z{z:.2f} F{feed_rate} ; Random move {i + 1}\n"
        )
        if i % 5 == 0:
            gcode_file.write(
                "G4 P500 ; Pause for 500ms to simulate dramatic pose\n"
            )  # Add a pause every 5 moves


# Function to write the Macarena dance and additional moves G-code to a file
def contemporary_dance_to_gcode(file_path):
    with open(file_path, "w") as gcode_file:
        # File header
        gcode_file.write("; Contemporary Dance G-code\n")
        gcode_file.write("; Generated by Python Script\n")
        gcode_file.write(f"; Date: {time.strftime('%Y-%m-%d %H:%M:%S')}\n")
        gcode_file.write("\n")

        # Printer initialization
        gcode_file.write("G21 ; Set units to millimeters\n")
        gcode_file.write("G90 ; Use absolute positioning\n")
        gcode_file.write("M82 ; Set extruder to absolute mode\n")
        gcode_file.write("G28 ; Home all axes\n")
        gcode_file.write("\n")

        # Starting position
        gcode_file.write("G1 X10 Y10 Z0.2 F1200 ; Move to starting position\n")

        # Initial "Macarena-style" dance moves
        gcode_file.write(
            "G1 X20 Y20 Z0.5 F1500 ; Move diagonally to arms front position 1\n"
        )
        gcode_file.write(
            "G1 X30 Y20 Z0.8 F1500 ; Move diagonally to arms front position 2\n"
        )
        gcode_file.write(
            "G1 X20 Y30 Z1.0 F1500 ; Move diagonally to arms shoulder position 1\n"
        )
        gcode_file.write(
            "G1 X30 Y30 Z1.2 F1500 ; Move diagonally to arms shoulder position 2\n"
        )
        gcode_file.write(
            "G1 X25 Y40 Z0.5 F1500 ; Move diagonally to arms head position\n"
        )
        gcode_file.write("G1 X10 Y40 Z0.2 F1500 ; Wiggle hips left\n")
        gcode_file.write("G1 X30 Y40 Z1.0 F1500 ; Wiggle hips right\n")
        gcode_file.write("G1 X20 Y10 Z0.5 F1500 ; Move diagonally down\n")

        # Contemporary dance section
        gcode_file.write("; Contemporary dance section begins\n")
        generate_dance_moves(gcode_file)
        gcode_file.write("; Contemporary dance section ends\n")

        # Return to home position
        gcode_file.write("G28 ; Return to home position\n")

        # File footer
        gcode_file.write("\n; End of Contemporary Dance G-code\n")


# File path for the output G-code file
gcode_file_path = "contemporary_dance.gcode"

# Write the contemporary dance to the G-code file
contemporary_dance_to_gcode(gcode_file_path)

print(f"G-code saved to {gcode_file_path}")
