import time


# Function to write the Macarena dance G-code to a file
def macarena_dance_to_gcode(file_path):
    with open(file_path, "w") as gcode_file:
        # File header
        gcode_file.write("; Macarena Dance G-code\n")
        gcode_file.write("; Generated by Python Script\n")
        gcode_file.write(f"; Date: {time.strftime('%Y-%m-%d %H:%M:%S')}\n")
        gcode_file.write("\n")

        # Printer initialization
        gcode_file.write("G21 ; Set units to millimeters\n")
        gcode_file.write("G90 ; Use absolute positioning\n")
        gcode_file.write("M82 ; Set extruder to absolute mode\n")
        gcode_file.write("G28 ; Home all axes\n")
        gcode_file.write("\n")

        # Starting position
        gcode_file.write("G1 X10 Y10 Z0.2 F1200 ; Move to starting position\n")

        # Macarena dance moves
        # Step 1: Arms to front
        gcode_file.write("G1 X20 Y20 ; Move diagonally to arms front position 1\n")
        gcode_file.write("G1 X30 Y20 ; Move diagonally to arms front position 2\n")

        # Step 2: Arms to shoulders
        gcode_file.write("G1 X20 Y30 ; Move diagonally to arms shoulder position 1\n")
        gcode_file.write("G1 X30 Y30 ; Move diagonally to arms shoulder position 2\n")

        # Step 3: Arms to head
        gcode_file.write("G1 X25 Y40 ; Move diagonally to arms head position\n")

        # Step 4: Wiggle hips
        gcode_file.write("G1 X10 Y40 ; Wiggle hips left\n")
        gcode_file.write("G1 X30 Y40 ; Wiggle hips right\n")
        gcode_file.write("G1 X20 Y10 ; Move diagonally down\n")

        # Repeat the sequence
        for _ in range(2):  # Repeat the sequence twice
            gcode_file.write("G1 X20 Y20 ; Arms to front position 1\n")
            gcode_file.write("G1 X30 Y20 ; Arms to front position 2\n")
            gcode_file.write("G1 X20 Y30 ; Arms to shoulders position 1\n")
            gcode_file.write("G1 X30 Y30 ; Arms to shoulders position 2\n")
            gcode_file.write("G1 X25 Y40 ; Arms to head position\n")
            gcode_file.write("G1 X10 Y40 ; Wiggle hips left\n")
            gcode_file.write("G1 X30 Y40 ; Wiggle hips right\n")
            gcode_file.write("G1 X20 Y10 ; Move diagonally down\n")

        # Return to home position
        gcode_file.write("G28 ; Return to home position\n")

        # File footer
        gcode_file.write("\n; End of Macarena Dance G-code\n")


# File path for the output G-code file
gcode_file_path = "macarena_dance.gcode"

# Write the Macarena dance to the G-code file
macarena_dance_to_gcode(gcode_file_path)

print(f"G-code saved to {gcode_file_path}")
